package com.utf.enums;

public enum ConfigProperties {
    URL,
    BROWSER,
    RUNMODE,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    APIBASEURL,
    DBURL,
    DBUSERNAME,
    DBPASSWORD,
    DBDRIVER
}